FROM node:latest
RUN apt-get install -y git
WORKDIR "/root"
RUN git clone https://github.com/nsuryabalaji/Sample_react_microservice_org.git
WORKDIR "/root/Sample_react_microservice_org/authservice/auth-app"
RUN npm install
EXPOSE 8080
ENTRYPOINT ["npm", "start"]

